In [2]:
import numpy as np

mat1 = np.array([[1,9,6],
        [7,99,88],
        [32,5,77]])
mat2 = np.array([[12,43,74],
        [87,85,3],
        [18,91,9]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))
     

The Sum of two matrix 

[[ 1  9  6]
 [ 7 99 88]
 [32  5 77]]  and 

[[12 43 74]
 [87 85  3]
 [18 91  9]]  is 

[[ 13  52  80]
 [ 94 184  91]
 [ 50  96  86]] 


In [4]:
import numpy as np

mat1 = np.array([[13,42,64],
        [34,70,4],
        [19,1,72]])
mat2 = np.array([[2,4,7],
        [55,67,8],
        [8,449,1]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[13 42 64]
 [34 70  4]
 [19  1 72]]  and 

[[  2   4   7]
 [ 55  67   8]
 [  8 449   1]]  is 

[[ 2848 31602   491]
 [ 3950  6622   802]
 [  669 32471   213]] 


In [1]:
def Matrix(n,v=0):
    M=[]             
    for i in range(n):
        
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def crMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def prMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 

def tpMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = crMatrix(n)

print("Display Array M1 In Matrix Form")
prMatrix(M1,n)

result = Matrix(n)
result = tpMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)      

Enter N for N x N matrix: 3
Enter the element :
34
12
76
56
44
98
65
34
65
Display Array M1 In Matrix Form
34 12 76 
56 44 98 
65 34 65 
Transposed Matrix
[34, 56, 65]
[12, 44, 34]
[76, 98, 65]


In [5]:
Arr = input("Enter string ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string I love maggi
I
love
maggi


In [8]:

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuationswow! what a weather!!
wow what a weather
